### ISSUE TITLE
Undeclared dependency for Pkg3 on 0.7

### ISSUE THREAD

**Issue by ghost** [oxinabox/DataDepsGenerators.jl#62]
On 0.7 and installed using Pkg3, `using DataDepsGenerators` fails with `ERROR: LoadError: ArgumentError: Package DataDepsGenerators does not have Missings in its dependencies`. This is currently blocking [JOSS review](https://github.com/openjournals/joss-reviews/issues/921).

**Comment by oxinabox** [comment]
The short when I sumbitted to JOSS I was looking at tagged release for julia 0.6.
which was DataDepsGenerators.jl v0.4.0

I believe master works with julia 0.7,
but it isn't extensively tested,
as julia 0.7 almost-working was merged because I was having a fight with @femtocleaner[bot].
#60 finishes it off.

Once #60 is done I will be more confidant that it will fully support julia 0.7 and julia 1.0.
#60 works locally for me, but is still having some travis issues.

**Comment by ghost** [comment]
My bad, do you want me to proceed with an 0.6 review of 0.4.0?

**Comment by oxinabox** [comment]
Up to you.
Feel free to wait for #60 to be merged.
It will be a smoother experience.
Because async works correctly.

And all the tests will be updated to match the fact that some upstream repos have taken files down etc.

**Comment by ghost** [comment]
Thanks, will proceed with 0.7 then as I expect that is where most of your users will be now that 0.6 is actively discouraged.

**Comment by oxinabox** [comment]
Closed in #60.

Julia 0.7 compat version is waiting to merge
https://github.com/JuliaLang/METADATA.jl/pull/18409
